(*
   Copyright 2008-2018 Microsoft Research

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*)
module FStar.Tactics.Typeclasses

open FStar.Tactics.Effect
open FStar.Stubs.Reflection.Types (* for `decls` *)

(*| The attribute that marks a typeclass instance, so that `FStar.Tactics.Typeclasses.tcresolve` can find it.

    The `instance` keyword adds it automatically. Resolution tries all instances in scope that carry this attribute. *)
val tcinstance : unit

(*| The attribute that marks a typeclass, which can be useful to control normalization or to generate code.

    The `class` keyword adds it automatically. See also `FStar.Tactics.Typeclasses.tcmethod`. *)
val tcclass  : unit
(*| The attribute that marks the methods of a typeclass, which can be useful to control normalization or to generate code.

    Added to the methods generated by `FStar.Tactics.Typeclasses.mk_class`. See also `FStar.Tactics.Typeclasses.tcclass`. *)
val tcmethod : unit

(*| An attribute declaring the functional dependencies of a class: the positions of the class arguments that are determined by the others.

    Positions count from `0` over all arguments, explicit and implicit alike. During resolution, if the arguments at these positions are unresolved (contain uvars) but the others are not, an instance can be applied and instantiate them; without functional dependencies, resolution does not try instances while some argument is unresolved. *)
val fundeps : list int -> unit

(*| An attribute on an instance that prevents it from instantiating the goal during resolution, even if the class has functional dependencies that seem to match.

    Such an instance is applied as with `FStar.Tactics.V2.Derived.apply_noinst`. *)
val noinst : unit

(*| An attribute on a class field to signal that no method should be generated for it. *)
val no_method : unit

(*| The typeclass resolution tactic: solves the current goal, a class constraint, from the instances in scope.

    It first tries the variables of the local context, then the global instances marked with `FStar.Tactics.Typeclasses.tcinstance`, recursively solving the constraints that an instance needs, with a bounded depth (a warning is logged if it is exhausted, which usually indicates a loop in the instances). Fails with "Could not solve typeclass constraint" if no solution is found. It is a plugin, so clients can run it without knowing its definition; it prints debugging information when `--debug Tac` is on. Implicit arguments written `#[tcresolve ()]` (as by `{| ... |}` binders) are solved with it. *)
val tcresolve : unit -> Tac unit

(*| Like `FStar.Tactics.Typeclasses.tcresolve`, but always prints debugging information. *)
val tcresolve_debug : unit -> Tac unit

(*| The metaprogram that generates the methods of a class (one projector-like function per field), given the class name.

    Also a plugin. The desugaring phase inserts it automatically for every `class` declaration; fields marked with `FStar.Tactics.Typeclasses.no_method` get no method. *)
val mk_class (nm:string) : Tac decls

(*| Returns an instance of type `a` found by typeclass resolution, as an explicit term.

    Use it to pass an instance explicitly where a value of a class type is expected.

    ```fstar
    let z' : has_zero int = FStar.Tactics.Typeclasses.solve
    ``` *)
[@@tcnorm]
unfold let solve (#a:Type) (#[tcresolve ()] ev : a) : Tot a = ev

(*| Like `FStar.Tactics.Typeclasses.solve`, but prints debugging information about the resolution, using `FStar.Tactics.Typeclasses.tcresolve_debug`. *)
[@@tcnorm]
unfold let solve_debug (#a:Type) (#[tcresolve_debug ()] ev : a) : Tot a = ev
