module FStar.Tactics.PrettifyType

open FStar.Bijection {}
open FStar.Tactics.V2.Bare

(* The single thing you should call here is entry function,
as the body of a splice. The rest of the declarations in this
interface are only in support of running the tactic, don't call
them directly. *)

(*| Marks a component of the type given to `FStar.Tactics.PrettifyType.entry` with a name, and is otherwise the identity on types.

    Around an atom, `s` is used as the field name; around the outer pair of a
    case, `s` is used as the constructor name. Without it, names are generated. *)
inline_for_extraction
type named (s:string) (a:Type) = a

(*| The quoted type `unit`, used internally by `FStar.Tactics.PrettifyType.entry`; not meant to be used directly. *)
let fakeunit = `unit

(*| States that `f` undoes `g` at the point `x`, i.e. `f (g x) == x`, as a squashed proposition.

    Used as the type of the inverse proofs generated by
    `FStar.Tactics.PrettifyType.entry`. *)
unfold
let f_inverses #a #b (f : b -> a) (g : a -> b) (x:a) =
  squash (f (g x) == x)

(*| A type that `FStar.Tactics.PrettifyType.entry` treats as a single field, represented by its term. *)
type atom = term

(*| The shape of a type being prettified by `FStar.Tactics.PrettifyType.entry`, as recognized by the tactic.

    - `Atom t` is a leaf type `t`, which becomes one field.
    - `Tuple2 l r` is a pair, whose fields are concatenated.
    - `Either l r` is a sum, whose cases become separate constructors.
    - `Named s t` is `t` wrapped in `FStar.Tactics.PrettifyType.named s`.

    Internal to the tactic; not meant to be used directly. *)
[@@plugin]
noeq
type parsed_type =
  | Atom   : atom -> parsed_type
  | Tuple2 : parsed_type -> parsed_type -> parsed_type
  | Either : parsed_type -> parsed_type -> parsed_type
  | Named  : string -> parsed_type -> parsed_type

(*| Proves the goal that the generated left map inverts the generated right map, for a type of the given shape; internal to `FStar.Tactics.PrettifyType.entry`.

    It introduces the argument, destructs it following the shape, and closes
    each case by `FStar.Tactics.V2.Derived.trefl`. Not meant to be called
    directly. *)
[@@plugin]
val prove_left_right (at : parsed_type) : Tac unit

(*| Proves the goal that the generated right map inverts the generated left map; internal to `FStar.Tactics.PrettifyType.entry`.

    It introduces the argument, destructs it by constructor, and closes each
    case by `FStar.Tactics.V2.Derived.trefl`. Not meant to be called directly. *)
[@@plugin]
val prove_right_left () : Tac unit

(*| Generates a readable inductive type equivalent to a type built from pairs and `either`, together with maps in both directions and proofs that they are inverses; use it as the body of a `%splice`.

    `nm` is the fully qualified name of the original type. Despite its name,
    `suf` is not a suffix: it is the unqualified name of the generated type,
    which is placed in the module of `nm`. For example, with
    `suf = "t_pretty"` it generates:

    - `t_pretty`: a non-recursive inductive with one constructor per case of the original type and one field per pair component of the case;
    - `t_pretty_right` and `t_pretty_left`: the maps from the original type to the new one and back;
    - `t_pretty_left_right` and `t_pretty_right_left`: proofs that the two maps are inverses, stated with `FStar.Tactics.PrettifyType.f_inverses`.

    Constructors are named `Mkt_pretty0`, `Mkt_pretty1` and so on, unless
    renamed with `FStar.Tactics.PrettifyType.named`. Only `tuple2` and
    `either` are decomposed: nest pairs instead of using `tuple3` and larger
    tuples. For example, `either ((int & int) & (int & string)) bool` gets two
    constructors, with fields `int`, `int`, `int`, `string` and `bool`
    respectively. The qualifiers and attributes of the `%splice` are propagated, where applicable, to
    the generated declarations. *)
[@@plugin]
val entry (suf nm : string) : Tac decls
