module FStar.Tactics.Parametricity

open FStar.Tactics.Effect
open FStar.Stubs.Reflection.Types

(* May be raised by the translations. *)
exception Unsupported of string
exception NotFoundFV of fv

(* Translate a term or type *)
(*| Computes the parametricity translation of a term or type.

    For a type `t`, the result is a relation of type `t -> t -> Type` relating
    two copies of a value of `t`; for a term `e : t`, it is a proof that `e` is
    related to itself by the translation of `t`. A top-level name `f` is
    translated to `f_param`, looked up next to `f` (as generated by
    `FStar.Tactics.Parametricity.paramd`) or else in this module, which
    provides relations such as `FStar.Tactics.Parametricity.int_param`. The translation fails, possibly by
    raising `FStar.Tactics.Parametricity.Unsupported` or
    `FStar.Tactics.Parametricity.NotFoundFV`, on terms it does not handle. *)
[@@plugin]
val param (t:term) : Tac term

(* Take a top-level declaration, of name nm, and generate
declarations for its parametricity translation. *)
(*| Generates the parametricity translation of the top-level declaration named `nm`, for use with `%splice`.

    The generated declaration is named after the last component of `nm` with
    the suffix `_param`, in the current module. A `let` gets a definition of
    the translated type; an inductive type gets a translated inductive whose
    constructors are also suffixed with `_param`. Fails if `nm` is not found,
    is a mutually recursive `let`, or is another kind of declaration. *)
[@@plugin]
val paramd (nm:string) : Tac decls

(* As above for several declarations at once. *)
(*| Like `FStar.Tactics.Parametricity.paramd`, for a list of names; the generated declarations are concatenated in order. *)
[@@plugin]
val paramds (nms:list string) : Tac decls

(* Parametricity principle for some base types. We should use
a typeclass for this. *)
(*| The parametricity relation of a type with decidable equality: two values are related exactly when they are equal.

    Used to define the relations of base types such as
    `FStar.Tactics.Parametricity.int_param`. *)
let param_of_eqtype (a:eqtype) : a -> a -> Type0 = (fun (x y : a) -> squash (x == y))
(*| The parametricity relation of `int`: equality.

    Found by `FStar.Tactics.Parametricity.param` when translating `int`. *)
let int_param    = param_of_eqtype int
(*| The parametricity relation of `bool`: equality. *)
let bool_param   = param_of_eqtype bool
(*| The parametricity relation of `unit`: equality. *)
let unit_param   = param_of_eqtype unit
(*| The parametricity relation of `string`: equality. *)
let string_param = param_of_eqtype string
